app/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/8/1 14:45
# @File    : Model.py
"""
数据模型
"""

from flask_login import LoginManager, login_user, UserMixin, logout_user, login_required
from app import login_manager
from app import db


class Users(UserMixin, db.Model):
    __tablename__ = 'py_user'  # 对应mysql数据库表
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    pwd = db.Column(db.String(64))

    def __init__(self, name, pwd):
        self.name = name
        self.pwd = pwd

    def get_id(self):
        return str(self.id)

    def __repr__(self):
        return '<User %r>' % self.name

    def is_authenticated(self):
        return True

    def is_active(self):
        if Users.query.filter_by(name=self.name).first():
            return True
        else:
            return False

    def is_anonymous(self):
        return False

class Ecs(db.Model):
    __tablename__ = 'py_ecs'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64))
    desc = db.Column(db.String(128))
    zone = db.Column(db.String(64))
    ip1 = db.Column(db.String(64), unique=True)
    ip2 = db.Column(db.String(64), unique=True)
    type = db.Column(db.String(64))
    cpu = db.Column(db.String(64))
    mem = db.Column(db.String(64))
    status = db.Column(db.String(64))
    ip1type = db.Column(db.String(64))
    tags = db.Column(db.String(64))

    def __init__(self, name, desc, zone, ip1, ip2, type, cpu, mem, status, ip1type, tags):
        self.name = name
        self.desc = desc
        self.zone = zone
        self.ip1 = ip1
        self.ip2 = ip2
        self.type = type
        self.cpu = cpu
        self.mem = mem
        self.status = status
        self.ip1type = ip1type
        self.tags = tags

    def is_active(self):
        if Ecs.query.filter_by(ip1 = self.ip1).first():
            return True
        else:
            return False

app/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/8/1 14:46
# @File    : Form.py
"""
表单类
"""

from wtforms import StringField, SubmitField, PasswordField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Length, ValidationError
from flask_wtf import FlaskForm
from .models import Users


# 登录表单
class Login_Form(FlaskForm):
    name = StringField('name', validators=[DataRequired(message='用户名不能为空'), Length(2, 6, message='用户名只能在2~6个字符之间')])
    pwd = PasswordField('pwd', validators=[DataRequired(message='密码不能为空'), Length(6, 20, message='密码只能在6~20个字符之间')])
    remember_me = BooleanField('remember me', default=False)
    submit = SubmitField('Login In')





# 注册表单
class Register_Form(FlaskForm):
    name = StringField('name', validators=[DataRequired()])
    pwd = PasswordField('pwd', validators=[DataRequired()])
    # confirm = PasswordField('确认密码', validators=[EqualTo('pwd', message='两次密码不一致')])
    submit = SubmitField('Sign up')

app/__init__.py
from flask import Flask,render_template,flash,url_for,redirect,Blueprint
from flask_bootstrap import Bootstrap
import logging
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from config import *
from flask_openid import OpenID
import os
import sys


#解决flash的一个bug
defaultencoding = 'utf-8'
if sys.getdefaultencoding() != defaultencoding:
    reload(sys)
    sys.setdefaultencoding(defaultencoding)


logging.basicConfig(filename='cmdb.log', level=logging.ERROR)
logging.info('Started')
app = Flask(__name__)
logging.info('App established')
#读取config配置
app.config.from_object('config')
# 初始化Flask-Bootstap扩展
bootstrap = Bootstrap()
mail = Mail()
moment = Moment()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'cmdb.login'
oid = OpenID(app, os.path.join(basedir, 'tmp'))


app.config.from_object(config['default'])
config['default'].init_app(app)
bootstrap.init_app(app)
mail.init_app(app)
moment.init_app(app)
db = SQLAlchemy(app)
db.init_app(app)
login_manager.init_app(app)

from app import views, models

app/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/8/1 14:45
# @File    : Views.py
"""
视图模型
"""

from  flask import render_template, Blueprint, redirect, url_for, flash, request, make_response, session
from app import login_manager, db
from .forms import Login_Form, Register_Form
from .models import Users
from flask_login import LoginManager, login_user, UserMixin, logout_user, login_required
from hashlib import md5
from .aliyun import AliyunEcs


cmdb = Blueprint('cmdb', __name__)  # 蓝图


@cmdb.route('/')
@cmdb.route('/index')
def index():
    if request.cookies.get('name'):
        return render_template('index.html', name=request.cookies.get('name'))
    else:
        form = Login_Form()
        return render_template('login.html', form=form)

@cmdb.route('/login', methods=['GET', 'POST'])
def login():
    form = Login_Form()
    if form.validate_on_submit():
        name = form.name.data
        pwd = form.pwd.data
        user = Users.query.filter_by(name=name).first()
        if user is not None and user.pwd == form.pwd.data:
            login_user(user)
            resp = make_response(redirect(url_for('cmdb.index', name=name)))
            resp.set_cookie(key='name', value=name, expires=None)
            resp.set_cookie(key='sessionId', value=str(md5((name+pwd).encode('utf8'))), expires=None)
            return resp
        else:
            flash('用户或密码错误')
            return render_template('login.html', form=form)


# 用户登出
@cmdb.route('/logout')
@login_required
def logout():
    logout_user()
    flash('你已退出登录')
    resp = redirect(url_for('cmdb.index'))
    resp.delete_cookie('name')
    resp.delete_cookie('sessionId')
    resp.delete_cookie('session')
    return resp


@cmdb.route('/register', methods=['GET', 'POST'])
def register():
    form = Register_Form()
    if form.validate_on_submit():
        user = Users(name=form.name.data,pwd=form.pwd.data)
        if user.is_active():
            flash("用户名已存在！")
        else:
            db.session.add(user)
            db.session.commit()
            flash('注册成功')
            return redirect(url_for('cmdb.register'))
    return render_template('register.html', form=form)

@login_manager.user_loader
def load_user(id):
     return Users.query.get(int(id))

@cmdb.route('/ecslist')
@login_required
def ecslist():
    aliyun_ecs = AliyunEcs()
    ecs_info = aliyun_ecs.Ecsinfo()
    return render_template('ecs.html', ecs_info=ecs_info)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}CMDB{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://v3.bootcss.com/examples/signin/signin.css" />
<style>
    body {
        background: white;
    }
    *{
        margin: 0;
        padding: 0;
    }
    html,body{
        height: 100%;
    }
    #container{
        /*保证footer是相对于container位置绝对定位*/
        position:relative;
        width:100%;
        min-height:100%;
        /*设置padding-bottom值大于等于footer的height值，以保证main的内容能够全部显示出来而不被footer遮盖；*/
        padding-bottom: 100px;
        box-sizing: border-box;
    }
    header{
        width: 100%;
        height: 200px;
        background: #999;
    }
    .main{
        width: 100%;
        height: 200px;
        background: orange;
    }
    footer{
        width: 100%;
        height:40px;   /* footer的高度一定要是固定值*/
        position:absolute;
        bottom:0px;
        left:0px;
        background: #333;
    }
    </style>
{% endblock %}



{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
    <script src="{{ url_for('static', filename='jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}" type="text/javascript"></script>
{% endblock %}

app/templates/ecs.html
{% extends "form_base.html" %}

{% block page_content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="nui-scroll">
        <div class="page-header">
            <p>{{ ecs_info }}</p>
        </div>
    </div>
</div>

{% endblock %}

app/templates/form_base.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <meta charset="utf-8">
    <style>
        #btn {
            margin: 5px;
            border-radius: 5px;
            color: white;
            border: none;
            padding: 5px 6px;
            float: right;
        }
        #box-title {
            font-size: 15px;
            font-weight: bold;
        }
        #box-content {
            height: 120px;
            padding: 5px 6px;
            border-top: 1px solid #e7eaec;
        }
        .box-content h3 {
            color: #428bca
        }
        .tabtop13 {
        	margin-top: 13px;
        }
        .tabtop13 td{
        	background-color:#ffffff;
        	height:25px;
        	line-height:150%;
        }
        .font-center{ text-align:center}
        .btbg{background:#e9faff !important;}
        .btbg1{background:#f2fbfe !important;}
        .btbg2{background:#f3f3f3 !important;}
        .biaoti{
        	font-family: 微软雅黑;
        	font-size: 26px;
        	font-weight: bold;
        	border-bottom:1px dashed #CCCCCC;
        	color: #255e95;
        }
        .titfont {
        	font-family: 微软雅黑;
        	font-size: 16px;
        	font-weight: bold;
        	color: #255e95;
        	background: url(../images/ico3.gif) no-repeat 15px center;
        	background-color:#e9faff;
        }
        .tabtxt2 {
        	font-family: 微软雅黑;
        	font-size: 14px;
        	font-weight: bold;
        	text-align: right;
        	padding-right: 10px;
        	color:#327cd1;
        }
        .tabtxt3 {
        	font-family: 微软雅黑;
        	font-size: 14px;
        	padding-left: 15px;
        	color: #000;
        	margin-top: 10px;
        	margin-bottom: 10px;
        	line-height: 20px;
        }
        footer{
        width: 100%;
        height:40px;   /* footer的高度一定要是固定值*/
        position:absolute;
        bottom:0px;
        left:0px;
        background: #333;
        }
        .nui-scroll{
            /*margin-left: 10px;*/
            border: 1px solid #000;
            width: auto;
            height: 650px;
            overflow: auto;
        }
        .nui-scroll::-webkit-scrollbar {
            width: 8px;
            height: 8px;
        }
        /*正常情况下滑块的样式*/
        .nui-scroll::-webkit-scrollbar-thumb {
            background-color: rgba(0,0,0,.05);
            border-radius: 10px;
            -webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1);
        }
        /*鼠标悬浮在该类指向的控件上时滑块的样式*/
        .nui-scroll:hover::-webkit-scrollbar-thumb {
            background-color: rgba(0,0,0,.2);
            border-radius: 10px;
            -webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1);
        }
        /*鼠标悬浮在滑块上时滑块的样式*/
        .nui-scroll::-webkit-scrollbar-thumb:hover {
            background-color: rgba(0,0,0,.4);
            -webkit-box-shadow: inset 1px 1px 0 rgba(0,0,0,.1);
        }
        /*正常时候的主干部分*/
        .nui-scroll::-webkit-scrollbar-track {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0);
            background-color: white;
        }
        /*鼠标悬浮在滚动条上的主干部分*/
        .nui-scroll::-webkit-scrollbar-track:hover {
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.4);
            background-color: rgba(0,0,0,.01);
        }

    </style>

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="http://img.chinaz.com/max-templates/passport/styles/topbar.css" type="text/css" rel="Stylesheet" />
    <link href="{{ url_for('static', filename='style_kj.css') }}" type="text/css" rel="stylesheet" />
    <link href="{{ url_for('static', filename='demo.css') }}" type="text/css" rel="stylesheet" />

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='ie10-viewport-bug-workaround.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{{ url_for('static', filename='ie-emulation-modes-warning.js') }}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('cmdb.index') }}">DevOps--CMDB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('cmdb.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('cmdb.index') }}">Log In</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cmdb.register') }}">Sign up</a></li>
            </ul>
        </div>
    </div>
</nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar" style="background-color: #2a6496">
          <ul class="nav nav-sidebar">
            <li><a href="{{ url_for('cmdb.ecslist') }}" style="">资产管理</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
          </ul>
          <!--<ul class="nav nav-sidebar">-->
            <!--<li><a href="">Nav item</a></li>-->
            <!--<li><a href="">Nav item again</a></li>-->
            <!--<li><a href="">One more nav</a></li>-->
            <!--<li><a href="">Another nav item</a></li>-->
            <!--<li><a href="">More navigation</a></li>-->
          <!--</ul>-->
          <!--<ul class="nav nav-sidebar">-->
            <!--<li><a href="">Nav item again</a></li>-->
            <!--<li><a href="">One more nav</a></li>-->
            <!--<li><a href="">Another nav item</a></li>-->
          <!--</ul>-->
        </div>
        <!--<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">-->
        <!--</div>-->
      </div>
    </div>
    <div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    </div>
    {% block page_content %}{% endblock %}
    <script src="{{ url_for('static', filename='jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}" type="text/javascript"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{{ url_for('static', filename='holder.min.js') }}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='ie10-viewport-bug-workaround.js') }}"></script>
  </body>
</html>

app/templates/index.html
{% extends "form_base.html" %}

{% block page_content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <div class="page-header">
        <h1>Hello,{{ name }}</h1>
    </div>
</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

<!--<div class="page-header">-->
 <!--<h1>Login</h1>-->
<!--</div>-->
    <link rel="stylesheet" href="https://v3.bootcss.com/examples/signin/signin.css" />
    <style>
    body {
        background-image: url(/static/background.jpg);
        background-repeat: no-repeat;
        background-size: 100% 100%;
        background-attachment: fixed;

    }
    .form-control {
    display: block;
    width: 100%;
    height: 34px;
    padding: 6px 12px;
    font-size: 14px;
    line-height: 1.42857143;
    color: #555;
    background-color: #fff;
    background-image: none;
    border: 1px solid #ccc;
    border-radius: 4px;
    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
    -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
    -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
    transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
}
    .control-label{ display: none;}

    .btn {
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: normal;
    line-height: 1.428571429;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
   }

    .btn-block {

    }
    .btn-default {
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;

    color: #fff;
    background-color: #337ab7;
    border-color: #2e6da4;
    display: block;
    width: 100%;
}
    .btn-primary {

}
    </style>

    <form action="/cmdb/login" method="post"  class="form-signin" style="width: 300px;height: 160px;position: fixed;left: 50%;top: 50%;margin-left: -150px;margin-top: -220px">

        <h1 align="center">CMDB运维平台</h1>
        <!--<h2 class="form-signin-heading">登录</h2>-->
        <!--{{ form.csrf_token }}-->
        <!--{{ wtf.quick_form(form) }}-->
        <label for="name" class="sr-only">name</label>
        <input type="text" id="name" name="name" class="form-control" placeholder="name" required autofocus>
        <label for="pwd" class="sr-only">Password</label>
        <input type="password" id="pwd" name="pwd" class="form-control" placeholder="Password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="Login In">登录</button>
        {{ form.csrf_token }}
    </form>

{% endblock %}

app/templates/register.html
<!DOCTYPE html>
{% import "bootstrap/wtf.html" as wtf %}
<html lang="zh-CN">
<head>
<style>
    .btn-default {
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;

    color: #fff;
    background-color: #337ab7;
    border-color: #2e6da4;
    display: block;
    }

    .btn {
    display: inline-block;
    padding: 6px 12px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: normal;
    line-height: 1.428571429;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    cursor: pointer;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
   }

    .btn-default {
    padding: 10px 16px;
    font-size: 18px;
    line-height: 1.3333333;
    border-radius: 6px;

    color: #fff;
    background-color: #337ab7;
    border-color: #2e6da4;
    display: block;
}
</style>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="{{ url_for('static', filename='bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{{ url_for('static', filename='ie10-viewport-bug-workaround.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
  <body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">DevOps--CMDB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('cmdb.logout') }}">Log Out</a></li>
                {% else %}
                <li><a href="{{ url_for('cmdb.index') }}">Log In</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="{{ url_for('cmdb.register') }}">Sign up</a></li>

            </ul>
        </div>
    </div>
</nav>
<div class="page-header">
 <h1>用户注册</h1>
</div>
    <div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    </div>
    <form action="/cmdb/register" method="post"  class="form-signin">
        {{ form.csrf_token }}
        {{ wtf.quick_form(form) }}
        <!--<label for="name" class="sr-only">name</label>-->
        <!--<input type="text" id="name" name="name" class="form-control" placeholder="name" required autofocus>-->
        <!--<label for="pwd" class="sr-only">Password</label>-->
        <!--<input type="password" id="pwd" name="pwd" class="form-control" placeholder="Password" required>-->
        <!--<button class="btn btn-lg btn-primary btn-block" type="submit" name="Sign up">Sign Up</button>-->
        <!--{{ form.csrf_token }}-->
    </form>
<!--<form action="/cmdb/register" method="post">-->
    <!--{{ wtf.quick_form(form) }}-->
<!--</form>-->

    <script src="{{ url_for('static', filename='jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='bootstrap.min.js') }}" type="text/javascript"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{{ url_for('static', filename='holder.min.js') }}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='ie10-viewport-bug-workaround.js') }}"></script>
  </body>
</html>